#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "----- Stoping puppetmaster -----"
service puppetmaster stop
echo "----- Starting cleanup -----"
rm /etc/puppet/modules/wso2bps /etc/puppet/modules/cleandb /etc/puppet/hieradata/ -rfv
echo "----- Copying Latest code -----"
cd $DIR/..
cp manifests/  modules/  hieradata/ fileserver.conf  hiera.yaml  puppet.conf /etc/puppet/ -rfv
echo "----- Staring puppetmaster -----"
service puppetmaster start
echo "----- Verify puppetmaster status -----"
service puppetmaster status 