---
hosts:
  manager.bps.wso2.com:
    name: manager.bps.wso2.com
    ip: 192.168.127.102
    comment: manager BPS node
    host_aliases: manager1
  mysql.bps.wso2.com:
    name: mysql.bps.wso2.com
    ip: 192.168.127.102
    comment: My SQL database server
    host_aliases: dbserver

nodes:
  manager1: 192.168.127.102

carbonHosts:
  manager.bps.wso2.com: 192.168.127.102